# Generated by Django 6.1.1 on 2026-09-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key', 'state'), name='unique_city_key_state')],
            },
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('price', models.FloatField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lon'], name='planner_fue_lat_fa6b04_idx')],
            },
        ),
    ]
